### ISSUE TITLE
Řazení členů předsednictva

### ISSUE THREAD

**Issue by Aktron** [pirati-web/praha.pirati.cz#12]
V předsednictvu na stránce https://praha.pirati.cz/lide/ by měli být uvedeni jeho členové v pořadí podle funkce (první předseda, poté místopředseda apod). Bohužel však přestože má Adam uvedeno "ordpks: 2" a Ondra "ordpks: 1", zobrazuje se Adam na 1. místě a Ondra na 4. místě. 

Také je možné, že pořadí lidí v předsednictvu určuje něco jiného než ordpks. Nevíte co?

**Comment by Kedrigern** [comment]
Opraveno
