### ISSUE TITLE
Prefix "Piráti:" před TZ přidělává práci, prosím odstranit

### ISSUE THREAD

**Issue by Aktron** [pirati-web/praha.pirati.cz#13]
Naše tiskové zprávy mají často slovo "Piráti" v názvu. Nešetří čas mít defaultní prefix pro každý článek (TZ) při vydávání, končí to většinou tím, že je nutné buď refrázovat název článku, nebo ho v případě zapomenutí měnit zpětně. Featuru by bylo dobré pro budoucí články vypnout, abychom se vyhnuli stavům typu "Piráti:Piráti vysílají do voleb pět kandidátů" "Piráti: V Praze vyšlou Piráti do voleb pět kandiátů" nebo "Piráti:Praha 1: Spáchali jsme zlo, spácháme jich víc. Piráti protestují."

**Comment by jitka** [comment]
Už jsem to dlouho neviděla, zavírám.
