### ISSUE TITLE
Nedostupné statické stránky

### ISSUE THREAD

**Issue by petrpulc** [pirati-web/praha.pirati.cz#29]
Prokliky z https://praha.pirati.cz/pripoj-se/ (např. https://praha.pirati.cz/pripoj-se/predsednictvo) nefungují, pravděpodobně kvůli špatnému nastavení serveru, kdy '.html' nejsou servírované při dotazu bez suffixu.

**Comment by petrpulc** [comment]
https://praha.pirati.cz/pripoj-se/piratske-listy-offline
(ze stejného místa)

**Comment by jitka** [comment]
dík, opraveno
